### ISSUE TITLE
Add support to validate the payment against a preimage

### ISSUE THREAD

**Issue by bumi** [dolcalmi/lnurl-pay#1]
I love your library and I think this makes using lnurl/lightning addresses from JS so much easier! thanks!

Once common pattern I see is that we get a bolt11 invoice through lnurl-pay and once paid check if the payment was successful by comparing the preimage to the payment hash. 

In this codepen I have an example of this: https://codepen.io/bumibumi/pen/GRMzbwe

Do you think this can be added?

**Comment by dolcalmi** [comment]
yep, do you think is enough with an utils method? 

ps: also I need to add LUD-10 support https://github.com/fiatjaf/lnurl-rfc/blob/luds/10.md

**Comment by bumi** [comment]
I think something like this could be useful?

```js
function validatePayment(paymentRequest, preimage) {
  const paymentHash = getPaymentHashFromPaymentRequest(paymentRequest);
  const preimageHash = sha256(preimage).toString(Hex);
  return paymentHash.toLowerCase() === preimageHash.toLowerCase();
}
```

so the library helps looking at the payment request and is doing all the hashing making it easy for the developer

**Comment by dolcalmi** [comment]
ok, done and published

you can use it with the returned `validatePreimage` method https://github.com/dolcalmi/lnurl-pay/blob/main/test/request-invoice.test.ts#L32 or with the helper function https://github.com/dolcalmi/lnurl-pay/blob/main/test/utils/is-valid-preimage.test.ts#L8

**Comment by bumi** [comment]
oh wow I love that validatePreimage method that is super cool and nice to use! thanks!
