### ISSUE TITLE
Missing LUD06 description hash verification

### ISSUE THREAD

**Issue by SamSamskies** [dolcalmi/lnurl-pay#15]
Step 7 in LUD06 says:
> LN WALLET Verifies that h tag in provided invoice is a hash of metadata string converted to byte array in UTF-8 encoding.

I believe to verify the description hash you can just compare the `metadataHash` that's returned from `parseLnUrlPayServiceResponse` with the `purpose_commit_hash` in the invoice. At least that's [what I'm doing on lnurlpay.com](https://github.com/SamSamskies/lnurlpay/blob/d6de15197ad19ff562790d7eabeb52a6593b5c25/pages/%5BlnUrlOrAddress%5D/%5Bamount%5D.tsx#L7-L12) and that seems to be working.

I was going to make a PR to do this, but I'm not sure how to update the invoices in the tests to include the appropriate description hash.

**Comment by dolcalmi** [comment]
Thanks for your contributions, fixed in [release 2.1.0](https://github.com/dolcalmi/lnurl-pay/releases/tag/v2.1.0)
