### ISSUE TITLE
support for onion urls?

### ISSUE THREAD

**Issue by dannydeezy** [dolcalmi/lnurl-pay#9]
seems that this does not work for onion urls, is that expected?

**Comment by dolcalmi** [comment]
https://github.com/dolcalmi/lnurl-pay#requestinvoice you have to set onionAllowed to true and pass fetchGet https://github.com/dolcalmi/lnurl-pay/blob/main/src/request-invoice.ts#L22 (for ex with something like `tor-request` package)

Hope it helps
